name: kog_friends
description: Amigos de KOG en línea y su servidor actual.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - flutter_01.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "flutter_01.png"
  min_sdk_android: 21
